<?php
/**
 * Mapping Engine Module
 *
 * Manages all field mappings between WooCommerce and Protheus systems.
 *
 * @package ABSLoja\ProtheusConnector
 * @since 1.0.0
 */

namespace ABSLoja\ProtheusConnector\Modules;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Mapping_Engine class
 *
 * Handles configuration and retrieval of field mappings between WooCommerce and Protheus.
 */
class Mapping_Engine {

	/**
	 * Option prefix for storing mappings
	 *
	 * @var string
	 */
	private const OPTION_PREFIX = 'absloja_protheus_';

	/**
	 * Constructor
	 */
	public function __construct() {
		// Initialize default mappings if not set
		$this->maybe_initialize_defaults();
	}

	/**
	 * Get customer field mapping (WooCommerce → Protheus SA1)
	 *
	 * @return array Customer field mapping configuration
	 */
	public function get_customer_mapping(): array {
		$default = array(
			'A1_FILIAL'  => '01',
			'A1_COD'     => '', // Generated by Protheus
			'A1_LOJA'    => '01',
			'A1_NOME'    => 'billing_first_name + billing_last_name',
			'A1_NREDUZ'  => 'billing_first_name',
			'A1_CGC'     => 'billing_cpf|billing_cnpj',
			'A1_TIPO'    => 'auto', // F or J based on document length
			'A1_END'     => 'billing_address_1',
			'A1_BAIRRO'  => 'billing_neighborhood',
			'A1_MUN'     => 'billing_city',
			'A1_EST'     => 'billing_state',
			'A1_CEP'     => 'billing_postcode',
			'A1_DDD'     => 'billing_phone',
			'A1_TEL'     => 'billing_phone',
			'A1_EMAIL'   => 'billing_email',
		);

		return get_option( self::OPTION_PREFIX . 'customer_mapping', $default );
	}

	/**
	 * Get order field mapping (WooCommerce → Protheus SC5/SC6)
	 *
	 * @return array Order field mapping configuration
	 */
	public function get_order_mapping(): array {
		$default = array(
			'SC5' => array(
				'C5_FILIAL'   => '01',
				'C5_NUM'      => '', // Generated by Protheus
				'C5_TIPO'     => 'N',
				'C5_CLIENTE'  => 'customer_code',
				'C5_LOJACLI'  => '01',
				'C5_CONDPAG'  => 'payment_method',
				'C5_TABELA'   => '001',
				'C5_VEND1'    => '000001',
				'C5_PEDWOO'   => 'order_id',
				'C5_EMISSAO'  => 'date_created',
				'C5_FRETE'    => 'shipping_total',
				'C5_DESCONT'  => 'discount_total',
			),
			'SC6' => array(
				'C6_FILIAL'  => '01',
				'C6_NUM'     => '', // Same as SC5
				'C6_ITEM'    => 'item_sequence',
				'C6_PRODUTO' => 'product_sku',
				'C6_QTDVEN'  => 'quantity',
				'C6_PRCVEN'  => 'unit_price',
				'C6_VALOR'   => 'line_total',
				'C6_TES'     => 'tes_code',
			),
		);

		return get_option( self::OPTION_PREFIX . 'order_mapping', $default );
	}

	/**
	 * Get product field mapping (Protheus SB1 → WooCommerce)
	 *
	 * @return array Product field mapping configuration
	 */
	public function get_product_mapping(): array {
		$default = array(
			'sku'               => 'B1_COD',
			'name'              => 'B1_DESC',
			'regular_price'     => 'B1_PRV1',
			'description'       => 'B1_DESC',
			'short_description' => 'B1_DESCMAR',
			'weight'            => 'B1_PESO',
			'status'            => 'B1_MSBLQL', // 1=draft, 2=publish
			'manage_stock'      => true,
			'stock_quantity'    => 0, // Updated by stock sync
			'category'          => 'B1_GRUPO',
		);

		return get_option( self::OPTION_PREFIX . 'product_mapping', $default );
	}

	/**
	 * Get payment method mapping (WooCommerce → Protheus payment conditions)
	 *
	 * @param string $woo_method WooCommerce payment method ID
	 * @return string|null Protheus payment condition code or null if not mapped
	 */
	public function get_payment_mapping( string $woo_method ): ?string {
		$default = array(
			'bacs'        => '001', // Bank transfer
			'cheque'      => '002', // Check
			'cod'         => '003', // Cash on delivery
			'credit_card' => '004', // Credit card
			'pix'         => '005', // PIX
		);

		$mapping = get_option( self::OPTION_PREFIX . 'payment_mapping', $default );

		return $mapping[ $woo_method ] ?? $mapping['cod'] ?? '003';
	}

	/**
	 * Get category mapping (Protheus B1_GRUPO → WooCommerce category ID)
	 *
	 * @param string $protheus_group Protheus product group code
	 * @return int|null WooCommerce category ID or null if not mapped
	 */
	public function get_category_mapping( string $protheus_group ): ?int {
		$default = array(
			'01' => 15, // Electronics
			'02' => 16, // Clothing
			'03' => 17, // Food
			'04' => 18, // Books
			'05' => 19, // Home & Garden
		);

		$mapping = get_option( self::OPTION_PREFIX . 'category_mapping', $default );

		return isset( $mapping[ $protheus_group ] ) ? (int) $mapping[ $protheus_group ] : null;
	}

	/**
	 * Get TES code by customer state (UF → TES code)
	 *
	 * @param string $state Brazilian state code (UF)
	 * @return string TES code for the state
	 */
	public function get_tes_by_state( string $state ): string {
		$default = array(
			'SP'      => '501', // Within state
			'RJ'      => '502', // Out of state
			'MG'      => '502',
			'ES'      => '502',
			'PR'      => '502',
			'SC'      => '502',
			'RS'      => '502',
			'BA'      => '502',
			'PE'      => '502',
			'CE'      => '502',
			'PA'      => '502',
			'MA'      => '502',
			'GO'      => '502',
			'MT'      => '502',
			'MS'      => '502',
			'DF'      => '502',
			'RO'      => '502',
			'AC'      => '502',
			'AM'      => '502',
			'RR'      => '502',
			'AP'      => '502',
			'TO'      => '502',
			'PI'      => '502',
			'RN'      => '502',
			'PB'      => '502',
			'AL'      => '502',
			'SE'      => '502',
			'default' => '502',
		);

		$mapping = get_option( self::OPTION_PREFIX . 'tes_rules', $default );

		return $mapping[ $state ] ?? $mapping['default'] ?? '502';
	}

	/**
	 * Get status mapping (Protheus → WooCommerce order status)
	 *
	 * @param string $protheus_status Protheus order status
	 * @return string WooCommerce order status
	 */
	public function get_status_mapping( string $protheus_status ): string {
		$default = array(
			'pending'   => 'pending',
			'approved'  => 'processing',
			'invoiced'  => 'completed',
			'shipped'   => 'completed',
			'cancelled' => 'cancelled',
			'rejected'  => 'failed',
		);

		$mapping = get_option( self::OPTION_PREFIX . 'status_mapping', $default );

		return $mapping[ $protheus_status ] ?? 'pending';
	}

	/**
	 * Validate mapping configuration
	 *
	 * @param string $type Mapping type (customer, order, product, payment, category, tes, status)
	 * @param array  $mapping Mapping configuration to validate
	 * @return array Array of validation errors (empty if valid)
	 */
	public function validate_mapping( string $type, array $mapping ): array {
		$errors = array();

		switch ( $type ) {
			case 'customer':
				$required_fields = array( 'A1_FILIAL', 'A1_NOME', 'A1_CGC', 'A1_END', 'A1_MUN', 'A1_EST' );
				foreach ( $required_fields as $field ) {
					if ( ! isset( $mapping[ $field ] ) || empty( $mapping[ $field ] ) ) {
						$errors[] = sprintf( 'Required field %s is missing or empty', $field );
					}
				}
				break;

			case 'order':
				if ( ! isset( $mapping['SC5'] ) || ! is_array( $mapping['SC5'] ) ) {
					$errors[] = 'SC5 mapping is required';
				}
				if ( ! isset( $mapping['SC6'] ) || ! is_array( $mapping['SC6'] ) ) {
					$errors[] = 'SC6 mapping is required';
				}
				break;

			case 'product':
				$required_fields = array( 'sku', 'name', 'regular_price' );
				foreach ( $required_fields as $field ) {
					if ( ! isset( $mapping[ $field ] ) || empty( $mapping[ $field ] ) ) {
						$errors[] = sprintf( 'Required field %s is missing or empty', $field );
					}
				}
				break;

			case 'payment':
			case 'category':
			case 'tes':
			case 'status':
				if ( ! is_array( $mapping ) ) {
					$errors[] = 'Mapping must be an array';
				}
				break;

			default:
				$errors[] = 'Invalid mapping type';
		}

		return $errors;
	}

	/**
	 * Save mapping configuration
	 *
	 * @param string $type Mapping type
	 * @param array  $mapping Mapping configuration
	 * @return bool True on success, false on failure
	 */
	public function save_mapping( string $type, array $mapping ): bool {
		$errors = $this->validate_mapping( $type, $mapping );
		if ( ! empty( $errors ) ) {
			return false;
		}

		$option_name = self::OPTION_PREFIX . $type . '_mapping';
		if ( 'tes' === $type ) {
			$option_name = self::OPTION_PREFIX . 'tes_rules';
		}

		return update_option( $option_name, $mapping );
	}

	/**
	 * Initialize default mappings if not already set
	 *
	 * @return void
	 */
	private function maybe_initialize_defaults(): void {
		// Check if mappings are already initialized
		if ( get_option( self::OPTION_PREFIX . 'mappings_initialized' ) ) {
			return;
		}

		// Initialize payment method mapping
		$payment_default = array(
			'bacs'        => '001', // Bank transfer
			'cheque'      => '002', // Check
			'cod'         => '003', // Cash on delivery
			'credit_card' => '004', // Credit card
			'pix'         => '005', // PIX
		);
		add_option( self::OPTION_PREFIX . 'payment_mapping', $payment_default );

		// Initialize TES rules by state
		$tes_default = array(
			'SP'      => '501', // Within state
			'RJ'      => '502', // Out of state
			'MG'      => '502',
			'ES'      => '502',
			'PR'      => '502',
			'SC'      => '502',
			'RS'      => '502',
			'BA'      => '502',
			'PE'      => '502',
			'CE'      => '502',
			'PA'      => '502',
			'MA'      => '502',
			'GO'      => '502',
			'MT'      => '502',
			'MS'      => '502',
			'DF'      => '502',
			'RO'      => '502',
			'AC'      => '502',
			'AM'      => '502',
			'RR'      => '502',
			'AP'      => '502',
			'TO'      => '502',
			'PI'      => '502',
			'RN'      => '502',
			'PB'      => '502',
			'AL'      => '502',
			'SE'      => '502',
			'default' => '502',
		);
		add_option( self::OPTION_PREFIX . 'tes_rules', $tes_default );

		// Initialize status mapping
		$status_default = array(
			'pending'   => 'pending',
			'approved'  => 'processing',
			'invoiced'  => 'completed',
			'shipped'   => 'completed',
			'cancelled' => 'cancelled',
			'rejected'  => 'failed',
		);
		add_option( self::OPTION_PREFIX . 'status_mapping', $status_default );

		// Initialize customer mapping
		$customer_default = array(
			'A1_FILIAL'  => '01',
			'A1_COD'     => '', // Generated by Protheus
			'A1_LOJA'    => '01',
			'A1_NOME'    => 'billing_first_name + billing_last_name',
			'A1_NREDUZ'  => 'billing_first_name',
			'A1_CGC'     => 'billing_cpf|billing_cnpj',
			'A1_TIPO'    => 'auto', // F or J based on document length
			'A1_END'     => 'billing_address_1',
			'A1_BAIRRO'  => 'billing_neighborhood',
			'A1_MUN'     => 'billing_city',
			'A1_EST'     => 'billing_state',
			'A1_CEP'     => 'billing_postcode',
			'A1_DDD'     => 'billing_phone',
			'A1_TEL'     => 'billing_phone',
			'A1_EMAIL'   => 'billing_email',
		);
		add_option( self::OPTION_PREFIX . 'customer_mapping', $customer_default );

		// Initialize order mapping
		$order_default = array(
			'SC5' => array(
				'C5_FILIAL'   => '01',
				'C5_NUM'      => '', // Generated by Protheus
				'C5_TIPO'     => 'N',
				'C5_CLIENTE'  => 'customer_code',
				'C5_LOJACLI'  => '01',
				'C5_CONDPAG'  => 'payment_method',
				'C5_TABELA'   => '001',
				'C5_VEND1'    => '000001',
				'C5_PEDWOO'   => 'order_id',
				'C5_EMISSAO'  => 'date_created',
				'C5_FRETE'    => 'shipping_total',
				'C5_DESCONT'  => 'discount_total',
			),
			'SC6' => array(
				'C6_FILIAL'  => '01',
				'C6_NUM'     => '', // Same as SC5
				'C6_ITEM'    => 'item_sequence',
				'C6_PRODUTO' => 'product_sku',
				'C6_QTDVEN'  => 'quantity',
				'C6_PRCVEN'  => 'unit_price',
				'C6_VALOR'   => 'line_total',
				'C6_TES'     => 'tes_code',
			),
		);
		add_option( self::OPTION_PREFIX . 'order_mapping', $order_default );

		// Initialize product mapping
		$product_default = array(
			'sku'               => 'B1_COD',
			'name'              => 'B1_DESC',
			'regular_price'     => 'B1_PRV1',
			'description'       => 'B1_DESC',
			'short_description' => 'B1_DESCMAR',
			'weight'            => 'B1_PESO',
			'status'            => 'B1_MSBLQL', // 1=draft, 2=publish
			'manage_stock'      => true,
			'stock_quantity'    => 0, // Updated by stock sync
			'category'          => 'B1_GRUPO',
		);
		add_option( self::OPTION_PREFIX . 'product_mapping', $product_default );

		// Initialize category mapping
		$category_default = array(
			'01' => 15, // Electronics
			'02' => 16, // Clothing
			'03' => 17, // Food
			'04' => 18, // Books
			'05' => 19, // Home & Garden
		);
		add_option( self::OPTION_PREFIX . 'category_mapping', $category_default );

		// Mark as initialized
		update_option( self::OPTION_PREFIX . 'mappings_initialized', true );
	}
}
