name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 217.21.92.134
          port: 22
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          timeout: 60s
          command_timeout: 30m
          script: |
            cd /var/www/html/absloja
            git pull origin main
            echo "✅ Deploy concluído!"
