name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 217.216.92.134
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/html/absloja
            git pull origin master
            echo "✅ Deploy concluído!"
